### ISSUE TITLE
Node error while running the code

### ISSUE THREAD

**Issue by varungupta85** [saurabhkirtani/dht11-azureIoT#1]
Hi, I attended the IoT workshop in Gurgaon during which we ran the exercise listed in this repo. After the workshop, I ordered a Raspberry Pi 3 and other items required for this exercise. I have followed the steps listed in the README and also installed the BCM 2835 library. I get the following error while running the program:

```
pi@raspberrypi:~/dht11-azureIoT/node $ sudo node index.js

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/pi/dht11-azureIoT/node/node_modules/node-dht-sensor/build/Release/node_dht_sensor.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/dht11-azureIoT/node/index.js:1:83)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I have removed all the azure related stuff and I am running below program to only output the sensor output on the console:

```
var sensorLib = require('node-dht-sensor');

var sensor = {
    initialize: function () {
        return sensorLib.initialize(11, 4);
    },
    read: function () {
        var readout = sensorLib.read();
        console.log('Temperature: ' + readout.temperature.toFixed(2) + 'C, ' +
            'humidity: ' + readout.humidity.toFixed(2) + '%');
    }
};

var connectCallback = function (err) {
  if (err) {
    console.error('Could not connect: ' + err.message);
  } else {
    console.log('Client connected');
    setInterval(function () {
            sensor.read();
        }, 2000);
  }
};


if (sensor.initialize()) {
  connectCallback();
} else {
    console.warn('Failed to initialize sensor');
}
```

I have tried running this using Node v6.3.0 and v4.4.7. Please let me know if you have any inputs on how to resolve this issue. Thanks!

**Comment by varungupta85** [comment]
I think I have found the solution. This [issue](https://github.com/Unitech/pm2/issues/1477) pointed towards the problem which was that I was using `nvm` to install node on Raspberry Pi but there was a node installed globally which was v.0.10.x and `npm install` command was picking up that version. I removed the `node` and `nodejs` commands from `/usr/bin` and I am able to run the experiment now. Thanks!

**Comment by saurabhkirtani** [comment]
Good to know. Feel free to comment back here for anything related.

**Comment by rooman130** [comment]
Hello Saurabh,

Kindly help us in DHT11-sensor git hub  experiment, Below is the message , everything is ok,but we fail to get sensor values and we checked DHT11 sensor is working fine.


pi@raspberrypi:~/dht11-azureIoT/node $ sudo node index.js
BCM2835 initialized.
Client connected
Temperature: 0.00C, humidity: 0.00%
Sending message back to the IoT Hub: {"DeviceId":1,"temperature":"0.00","unitOfTemp":"C","humidity":"0.00","unitOfHumidity":"%","TimeFlag":"2017-05-30T13:03:37.526Z"}
send status: MessageEnqueued--------------------------------------------

**Comment by brijrajsingh** [comment]
Please send a picture of your wiring

**Comment by rooman130** [comment]
Thanks Brijraj,

1.We are using BCM 2837 in Raspberry pi 3 B+ model, but the BCM 2835 is
installed ,is this not compatible with GPIO being used for wiring ??

2.Are there any issues with wrapping/binding the Node DHT 11 sensor ( C/C++
files) ??
3.Do you advice any wiring standard to be used in the index.js file ?


Looking for solution..
Shyam
